background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 4
    contrast = 0.9
    brightness = 0.5
    vibrancy = 0.16
    vibrancy_darkness = 0.1
}

label {
    monitor =
    text = $TIME
    color = rgba(@base05@ff)
    font_size = 110
    font_family = JetBrains Mono ExtraBold
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(@base04@e6)
    font_size = 20
    font_family = JetBrains Mono
    position = 0, 20
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(@base0A@cc)
    inner_color = rgba(@base00@99)
    font_color = rgba(@base05@ff)
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = <i>󰌾 Введите пароль...</i>
    hide_input = false
    rounding = -1
    check_color = rgba(@base0B@cc)
    fail_color = rgba(@base08@cc)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT
    color = rgba(@base04@cc)
    font_size = 14
    font_family = JetBrains Mono
    position = 0, -150
    halign = center
    valign = center
}
